### ISSUE TITLE
All tabs missing in "Properties" window after install

### ISSUE THREAD

**Issue by dannn-o** [linux-man/nemo-mediainfo-tab#1]
After problems with the mediainfo.nemo_action method for displaying Mediainfo information, I saw your post in the Linux Mint bug report and gave it a try.  However, after installing the plugin (I tried both the PPA and the .DEB package), there are no tabs at all visible when viewing the properties window for an audio file.  Please see the attached screen shot.
![media-info-tab](https://user-images.githubusercontent.com/17674969/44066454-5fc4d05c-9f3e-11e8-8cf1-8ea356d1dace.png)

I am using Linux Mint 18.3 Cinnamon (64-bit) with Cinnamon 3.6.7.  Nemo version is 3.6.5.  After uninstalling the plugin, the normal tabs are visible again (Basic, Permissions, Open With, etc).

**Comment by linux-man** [comment]
I'm on vacations so I can't give you great help.
It happens on all media files or just that one?
Can you close/open Nemo on console and take a look at messages when starting and opening properties window?
Also, could you try to use the default theme?

**Comment by dannn-o** [comment]
No problem.  I am starting vacation very soon as well.  If I don't have a chance to try what you suggested before, I will when I get back.  The issue seemed to happen on any media file.

**Comment by linux-man** [comment]
Closing due to lack of news.
