### ISSUE TITLE
Adding support for subtitles

### ISSUE THREAD

**Issue by igorer88** [linux-man/nemo-mediainfo-tab#10]
Would be nice if it can be added the support for diferents formats of subtitles, since they are a part of a media file. 

https://wiki.videolan.org/Subtitles/
Here is a list of the some of them, we could start by the most used formats (.srt and .ssa/.ass), and keep adding them as we go.

**Comment by linux-man** [comment]
Mediainfo-tab format and shows mediainfo lib output. Although this library supports subtitles formats, the information it presents is minimal and there is really no advantage to show it. You can check that
`mediainfo "something.srt"` output is
> General
> Complete name                            : something.srt
> File size                                : 40.1 KiB
 
What nemo-mediainfo do is show the library output if the number of lines is bigger than 7. Besides media files, PDF is the only format that shows something more than file size.
