### ISSUE TITLE
Not working anymore on Mint 19.3 Cinnamon

### ISSUE THREAD

**Issue by cypherpunk1984** [linux-man/nemo-mediainfo-tab#11]
Was working great but after some update on the last months or so, it stopped working. I think has something to do with new versions of Python maybe?
Tried uninstalling and installing again and nothing, the tab doesn't show. Going to Plugins on Nemo and it is not there.
I use the PPA and it downloads version 1.0, I haven't manually downloaded version 1.03 because it says is for Focal, not Bionic, should I try anyway?
I hope I can fix it, it is a great tool, I love it.
Thank you.

**Comment by linux-man** [comment]
I'm using Focal, so I'm not following Bionic changes.
You can launch Nemo on console and search for any output error related to nemo-mediainfo-tab.
If there was any python or mediainfo lib upgrade, please try 1.03 version, if dependencies allow it.

**Comment by cypherpunk1984** [comment]
Thanks for your help!

Nemo on terminal throws this error:

```
File "/usr/share/nemo-python/extensions/nemo-mediainfo-tab.py", line 16, in <module>
    from MediaInfoDLL3 import *
ImportError: No module named MediaInfoDLL3
```

Tried 1.03 and same result

I see on the closed issues that someone was having a similar problem 2 years ago but with an Arch based distro:
https://github.com/linux-man/nemo-mediainfo-tab/issues/3
Difference is that their error said MediaInfoDLL, my error says MediaInfoDLL3 and it is in a different line. Looks like Ubuntu devs changed something on the latests python updates for 18.04 maybe? Is there something I can do to fix it?

**Comment by linux-man** [comment]
I didn't find any major change regarding libraries - and that changes are very rare on a LTS.
Did Nemo had a major upgrade (from 3 to 4)?
Question is:
Nemo 3 uses python 2 and nemo-mediainfo-tab uses python-mediainfodll package.
Nemo 4 uses python 3 and nemo-mediainfo-tab uses python3-mediainfodll package.
The issue you found was created because Arch just upgraded Nemo.
To solve the issue, nemo-mediainfo search for both libraries.
```
try:
  from MediaInfoDLL import *
except ImportError:
  from MediaInfoDLL3 import *
```
One of them most work! Please confirm your Nemo version and which mediainfodll library is installed.
It's probably better to downgrade nemo-mediainfo-tab to 1.0.

**Comment by cypherpunk1984** [comment]
> Did Nemo had a major upgrade (from 3 to 4)?

Yes, I just realized Mint devs pushed an upgrade. Ubuntu's 18.04 repo still has nemo 3.6.5, but on Mint's 19.3 repo, nemo was recently upgraded to 4.4.3.

My system has python3-mediainfodll package installed and Nemo 4.4.3. And yes I downgraded to nemo-mediainfo-tab to 1.0

Didn't understand what should I do to solve this with the code you typed. Could you instruct me on what to do please?

Thanks a lot for your help.

**Comment by linux-man** [comment]
This code is part of the plugin. I'm installing 19.3 on VirtualBox and I'll look into it.

**Comment by linux-man** [comment]
![mint](https://user-images.githubusercontent.com/1733538/103430422-d33eae00-4bbb-11eb-8e22-ce7dcf505f8d.jpg)
Bad news! It works on a plain fully upgraded installation.
Search and uninstall python-mediainfodll package.
You can also remove nemo-mediainfo-tab and all mediainfo packages, and try to reinstall.
Let's see if it changes anything.

**Comment by cypherpunk1984** [comment]
> Bad news! It works on a plain fully upgraded installation.

Oh noooo, so it's a problem with my system.

> Search and uninstall python-mediainfodll package.

There is no python-mediainfodll in my system. Only python3-mediainfodll.

> You can also remove nemo-mediainfo-tab and all mediainfo packages, and try to reinstall.

Tried that, no changes.

Could it be that one of other extensions I use is creating a conflict or something like that? Here is the complete feedback when opening nemo from terminal:

```
Initializing Nextcloud-client-nemo extension
Using python version sys.version_info(major=2, minor=7, micro=17, releaselevel='final', serial=0)
Could not connect to unix socket /run/user/1000/Nextcloud/socket. [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo-mediainfo-tab.py", line 16, in <module>
    from MediaInfoDLL3 import *
ImportError: No module named MediaInfoDLL3
Initializing nemo-image-converter extension
Nemo-Share-Message: 20:37:08.389: Called "net usershare info" but it failed: 'net usershare' returned error 255: mkdir failed on directory /var/run/samba/msg.lock: Permission denied
net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory
Please ask your system administrator to enable user sharing.

Could not connect to unix socket /run/user/1000/Nextcloud/socket. [Errno 2] No such file or directory
Could not connect to unix socket /run/user/1000/Nextcloud/socket. [Errno 2] No such file or directory
Could not connect to unix socket /run/user/1000/Nextcloud/socket. [Errno 2] No such file or directory
```

Thank you so much for your time, and for trying to help me solve it.

**Comment by linux-man** [comment]
That's too weird. Maybe it's a "cache" problem. Remove nemo-mediainfo and look at compiled python files. Delete "/usr/share/nemo-python/extensions/nemo-mediainfo-tab" if present. Delete all .pyc files at "/usr/share/nemo-python/extensions" and delete "/usr/share/nemo-python/extensions/\_\_pycache\_\_" folder. Reinstall.

**Comment by cypherpunk1984** [comment]
Already tried that. I even deleted the MediaInfoDLL3.pyc in "usr/lib/python3/dist-packages/__pycache__". No changes.

Isn't it weird that there is a python2.7 folder in "usr/lib/"? and when nemo starts, terminal says:

`Using python version sys.version_info(major=2, minor=7, micro=17, releaselevel='final', serial=0)`

Shouldn't it be using python 3 instead of 2.7?

It is driving me crazy, I don't know what else to try. Thanks so much though, I think I'll have to live without the extension.

I'm planning to upgrade to Mint 20 in a next couple of months, maybe that will hopefully fix it.

**Comment by linux-man** [comment]
On my 19.3 I don't get "Using python version" line.
Can it be nemo-nextcloud extension that's outdated and force python 2?
Next step is to remove/disable all nemo extensions you use.
On Focal/Mint 20 all repositories have Nemo 4. This problem should go away.

**Comment by cypherpunk1984** [comment]
It worked! You got it right! nemo-nexcloud extension was forcing nemo to use python 2.7, and nemo-mediainfo-tab couldn't find MediaInfoDLL3 nor MediaInfoDLL because of that, it was probably looking for it in the python 2.7 folder instead of the python 3 one. After removing nemo-nextcloud extension and deleting cache files, everything works great, I don't even get errors anymore when opening nemo from terminal (there was plenty when nemo-nextcloud was installed).

I'll create an issue on the nextcloud extension repo so people are warned of how outdated and how bad it works. I can't believe one simple extension can force the file manager to use an outdated version of python for everything else, it is outrageous.

Thank you so much for your time and your help! I'm so happy I have the Media Info tab again! I love it! Great work with it! Keep it up!

**Comment by linux-man** [comment]
Don't be too harsh. Considering the repository where it stands and the nemo version you find there (bionic/universe), that extension works perfectly well.
Maybe cherry-picking some packages from focal, like https://packages.ubuntu.com/focal/nemo-nextcloud can do the trick.
