### ISSUE TITLE
AcoustID-fingerprint tag makes properties window ultra wide

### ISSUE THREAD

**Issue by DaisyF8** [linux-man/nemo-mediainfo-tab#12]
I use Picard Musicbrainz to fingerprint-id my audio files.  Those descriptions are thousands characters long.

Mediainfo-tab displays that string in full... Maybe it shouldn't :)

![Screenshot_2021-09-01_11-25-11](https://user-images.githubusercontent.com/10348988/131647138-99b28749-a7e6-41b9-95fb-d6c6a18a8074.png)

**Comment by linux-man** [comment]
Yes! It's humongous!
Don't know what's better: to add it to the exclude list, or to strip all strings bigger than x characters.
Can you send a small sample of your file? My window never gets that big.

**Comment by DaisyF8** [comment]
The flac file you mean ? Do you have an emailadres I can use ?

**Comment by linux-man** [comment]
*********@*******.***

**Comment by DaisyF8** [comment]
Sent.

The acoustid-fingerprint is probably just a raw version of the derived acoustid...  So nothing is lost by cutting that tag down in size when you display it.  Excluding it all together wouldn't be good because then I would need to open the file in another program to see if a fingerprint had been generated.  But maybe displaying something like "12563-digits fingerprint present" would be okay.

**Comment by linux-man** [comment]
Didn't receive. File too big?

**Comment by DaisyF8** [comment]
There was no file in the email, but a wetransfer-link. I sent it yesterday 18:04 UTC...

**Comment by DaisyF8** [comment]
![Screenshot_20210902-101158_Outlook](https://user-images.githubusercontent.com/10348988/131808260-aeaee90e-e47f-46d2-8614-e816accf750e.jpg)

**Comment by linux-man** [comment]
Got it. Thanks.

**Comment by linux-man** [comment]
New release. Please try it.

**Comment by DaisyF8** [comment]
(I'm a beginner)

I downloaded the new version souce code and untarred it.  All I need to do in the script location  is :
`sudo cp '/home/Df8/Desktop/nemo-mediainfo-tab-1.0.4/nemo-extension/nemo-mediainfo-tab.py' .
cp: overwrite './nemo-mediainfo-tab.py'? yes`
right ?

Whenever I use your new version, I don't have the tab anymore... Nemo says :
`Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo-mediainfo-tab.py", line 13, in <module>
    from MediaInfoDLL3 import *
ModuleNotFoundError: No module named 'MediaInfoDLL3'
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo-mediainfo-tab.py", line 13, in <module>
    from MediaInfoDLL3 import *
ModuleNotFoundError: No module named 'MediaInfoDLL3'
`
I have both mediainfo and libmediainfo installed... I'm on manjaro.

Any suggestions ? I don't think I have a lot of dll's on my system lol.

 (leaving soon so could take a whole day until next feedback)

**Comment by linux-man** [comment]
Just update your package. @yochananmarqos was extra-efficient and AUR is already synchronized.

**Comment by DaisyF8** [comment]
Fixed, awesome. Thank you.
