### ISSUE TITLE
Compatible with Nemo on Fedora?

### ISSUE THREAD

**Issue by wunderox** [linux-man/nemo-mediainfo-tab#13]
Is there any way to make this work in Nemo on Fedora?

EDIT: I was able to convert the *.deb file to an *.rpm file and it installed just fine, but the tab doesn't show up, even after restarting the machine.

**Comment by linux-man** [comment]
Did you install nemo-python package? Or python3-nemo

**Comment by linux-man** [comment]
Another needed package is python3-mediainfo

**Comment by wunderox** [comment]
Thank you for your response. I didn't know those packages were required. Could you point me to where those instructions are provided?

I installed `python3-nemo` but I couldn't find any `python3-mediainfo` package for dnf. Are you sure about the name?
Additionally, is there any specific order in which the packages should be installed?

**Comment by linux-man** [comment]
Sorry, but since it's a debian install I didn't publish the dependencies. You can find them at debian/control file.
You can find python3-mediainfo at https://mediaarea.net/en/Repos. It's not the same as python-pymediainfo - a different wrapper.
Downloads at https://mediaarea.net/repo/rpm/snapshots/Fedora_36/x86_64/RPMS/

**Comment by wunderox** [comment]
Thank you for your quick response.
I followed the link and tried installing the `python3-mediainfo-22.06.20220702.x86_64.Fedora_36.MediaArea.rpm` file but I got the following error:
```
Error: 
 Problem: conflicting requests
  - nothing provides libmediainfo(x86-64) = 22.06.20220702 needed by python3-mediainfo-22.06.20220702-1.1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```
I tried to run
`sudo dnf install libmediainfo` but it didn't solve the problem. Any thoughts?

**Comment by linux-man** [comment]
[libmediainfo](https://mediaarea.net/repo/rpm/snapshots/Fedora_36/x86_64/RPMS/libmediainfo-22.06.20220702.x86_64.Fedora_36.MediaArea.rpm) is at the same folder. You must install it first, or just add mediaarea repo, as instructed at https://mediaarea.net/en/Repos.

**Comment by wunderox** [comment]
You're right. I tried installing `libmediainfo` but it says:
```
Error: 
 Problem: conflicting requests
  - nothing provides libstdc++.so.6(GLIBCXX_3.4.30)(64bit) needed by libmediainfo-22.06.20220702-1.1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```
It seems the latest version I have is `GLIBCXX_3.4.29` when checking using `strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX`.
From what I understand this is not a library I can simply install, so I guess I'm just out of luck?

**Comment by wunderox** [comment]
I just checked, for whatever reason I now have the fourth tab in the properties and it displays properties for images though not for mp4 or avi. I only checked for videos before so I don't know if it used to display properties for images when I first installed it.

**Comment by linux-man** [comment]
That's weird. Just check your fedora version. I can find https://pkgs.org/download/libstdc++.so.6(GLIBCXX_3.4.30)(64bit) for Fedora 36, but I'm a Debian user for too long. Can't help you that much about rpm repos and dependencies.
You found an Image system tab (nice one), not "the" Medianfo tab.

**Comment by wunderox** [comment]
I'm running fedora 35, I didn't realize there was a newer version, I'm in the process of upgrading.

**Comment by wunderox** [comment]
Alright, so I upgraded to Fedora 36 and all the installation steps worked like a charm.
Just for completeness, I basically installed (from here: https://mediaarea.net/repo/rpm/snapshots/Fedora_36/x86_64/RPMS/):
```
libmediainfo-22.06.20220702.x86_64.Fedora_36.MediaArea.rpm
python3-mediainfo-22.06.20220702.x86_64.Fedora_36.MediaArea.rpm
```
And the following had been installed previously:
`sudo dnf install python3-nemo` and `nemo-mediainfo-tab_1.0.4_all.deb` (converted to an `*.rpm` file using `sudo alien -r nemo-mediainfo-tab_1.0.4_all.deb` and installed using `sudo dnf install nemo-mediainfo-tab-1.0.4-2.noarch.rpm`.

Also make sure to restart your file browser for the changes to take effect. The changes should provide with a new tab named `Media Info` when right clicking a media file and selecting properties.

Perhaps it helps for anyone else who'd try to install this on Fedora.

Edit: added links for completeness.
Edit2: Thank you for your help @linux-man
