### ISSUE TITLE
Please use "python-nemo | nemo-python" in the depends field for deb packages

### ISSUE THREAD

**Issue by logix2** [linux-man/nemo-mediainfo-tab#2]
In Linux Mint, the Nemo Python package binary is named ``python-nemo`` while Ubuntu uses ``nemo-python``. So this doesn't work for users installing Nemo from the Ubuntu (and I guess Debian too) repositories.

The Linux Mint binary package: [http://packages.linuxmint.com/pool/backport/n/nemo-python/](http://packages.linuxmint.com/pool/backport/n/nemo-python/)
The Ubuntu 18.04 binary package: [https://launchpad.net/ubuntu/+source/nemo-python/3.6.0-1/+build/14498276](https://launchpad.net/ubuntu/+source/nemo-python/3.6.0-1/+build/14498276)

Using ``python-nemo | nemo-python`` in the ``Depends:`` field of the ``control`` file should allow installing this package with both the Ubuntu and Linux Mint Nemo Python packages.

**Comment by linux-man** [comment]
Done. Please try to update and test.

**Comment by logix2** [comment]
All good now, thank you.
