### ISSUE TITLE
ImportError: No module named MediaInfoDLL

### ISSUE THREAD

**Issue by yochananmarqos** [linux-man/nemo-mediainfo-tab#3]
I installed this on Manjaro Cinnamon and get the following error running Nemo:

```
$ nemo
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo-mediainfo-tab.py", line 9, in <module>
    from MediaInfoDLL import *
ImportError: No module named MediaInfoDLL
```
The following files are from [`libmediainfo`](https://www.archlinux.org/packages/community/x86_64/libmediainfo/files/):
```
$ ls /usr/include/MediaInfoDLL
MediaInfoDLL.h  MediaInfoDLL_Static.h
```

**Comment by linux-man** [comment]
Try to install python-pymediainfo package.

**Comment by yochananmarqos** [comment]
I have `python2-pymediainfo` installed. `python-pymediainfo` is for `python` 3.7.

**Comment by linux-man** [comment]
It looks like the official python binding was not packaged on Arch. pymediainfo is a different project.
Can you try to add [MediaInfoDLL.py](https://github.com/MediaArea/MediaInfoLib/tree/master/Source/MediaInfoDLL) to
a) the extension folder (you'll probably need to change import to relative like "from .MediaInfoDLL import *")
or
b) the python packages folder - on Debian is at /usr/lib/python2.7/dist-packages/

**Comment by yochananmarqos** [comment]
I tried installing `nemo-mediainfo-tab.py` and `MediaInfoDLL.py` to `/usr/share/nemo-mediainfo-tab` and symlinking `nemo-mediainfo-tab.py` to `/usr/share/nemo-python/extensions`. Changing `from MediaInfoDLL import *` to `from .MediaInfoDLL import *` made no difference.

I don't have a `/usr/lib/python2.7/dist-packages` folder.  
[`$ tree /usr/lib/python2.7`](https://pastebin.com/3CczK2cu)

**Comment by ghost** [comment]
I've just got this to work on Arch. I don't like putting stuff that doesn't belong to a package in ``/usr``, so I did everything in my home. This is what I did (create the directories if they don't exist):

```bash
wget -O ~/.local/lib/python2.7/site-packages/MediaInfoDLL.py https://raw.githubusercontent.com/MediaArea/MediaInfoLib/master/Source/MediaInfoDLL/MediaInfoDLL.py
wget -O ~/.local/share/nemo-python/extensions/nemo-mediainfo-tab.py https://raw.githubusercontent.com/linux-man/nemo-mediainfo-tab/master/nemo-extension/nemo-mediainfo-tab.py
sed -i 's,/usr/bin/python,/usr/bin/python2,'  ~/.local/share/nemo-python/extensions/nemo-mediainfo-tab.py
nemo -q
```

Seems to work fine so far, if I find time I'll add this package and python-mediainfodll to the AUR.

**Comment by linux-man** [comment]
That would be great!

**Comment by yochananmarqos** [comment]
@Corax26 How's this PKGBUILD for now? I don't think `makepkg` will allow installing to $HOME.

```
pkgname=nemo-mediainfo-tab
pkgver=0.2
pkgrel=1
pkgdesc="View media information from the properties tab"
arch=('any')
url="https://github.com/linux-man/nemo-mediainfo-tab"
license=('GPL3')
depends=('libmediainfo' 'nemo-python')
provides=('nemo-mediainfo-tab')
source=("$pkgname-$pkgver.tar.gz::$url/archive/v$pkgver.tar.gz"
        "https://raw.githubusercontent.com/MediaArea/MediaInfoLib/master/Source/MediaInfoDLL/MediaInfoDLL.py")
md5sums=('b0fbb2ac22ef1dec43fa257eae6d4a44'
         'a0a28b4f54082cbf28fe9c0d405775a8')

prepare() {
    sed -i 's,/usr/bin/python,/usr/bin/python2,' ${pkgname}-${pkgver}/nemo-extension/${pkgname}.py
}

package() {
    install -D -m644 ${pkgname}-${pkgver}/nemo-extension/${pkgname}.py ${pkgdir}/usr/share/nemo-python/extensions/${pkgname}.py
    install -D -m644 MediaInfoDLL.py ${pkgdir}/usr/lib/python2.7/site-packages/MediaInfoDLL.py
}
```

**Comment by linux-man** [comment]
Looks fine, but shouldn't python-mediainfodll be another package?

**Comment by yochananmarqos** [comment]
Yes, but I'm not sure what to use as the source. I want to avoid downloading the whole MediaInfoLib project just for one file. Or just use the one file as the source? It looks like that's all that's in the [Debian package](https://packages.debian.org/jessie/all/python-mediainfodll/filelist).

**Comment by linux-man** [comment]
Just use the py file with a dependency on libmediainfo.

**Comment by ghost** [comment]
@yochananmarqos Sure, putting stuff in your $HOME is appropriate when doing things manually, but packaged stuff must go to the system-wide locations ( so `/usr`). As @linux-man said, python-mediainfodll must be a separate package. Don't forget to add the relevant license file as well. The easiest approach is to base your PKGBUILD on an existing Python package, for instance: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/python-appdirs

**Comment by linux-man** [comment]
I also notice that most PKGBUILD creators use the zip of releases or tags to have some control of the version.

**Comment by ghost** [comment]
Indeed, a normal package has a static version so the sources must be a release. There are also -git packages that check out the git repo directly and generate a version from the HEAD commit, but as long as you release regularly, that shouldn't be needed :) BTW, forgot to thank you @linux-man, this plugin is actually clearer than MediaInfo's HTML view, and I'm impressed by how straightforward the code is :D

**Comment by yochananmarqos** [comment]
Something like this then?
```
pkgname=python-mediainfodll
_pkgname=MediaInfoLib
pkgver=18.05
pkgrel=1
pkgdesc="library for reading metadata from media files -- shared library"
arch=('any')
url="https://github.com/MediaArea/MediaInfoLib"
license=('BSD 2-Clause')
depends=('libmediainfo')
provides=('python-mediainfodll')
source=("$_pkgname-$pkgver.tar.gz::$url/archive/v$pkgver.tar.gz")
md5sums=('59e9523c472a77f5b23ca3c072595161')

package() {
    install -Dm644 ${_pkgname}-${pkgver}/Source/MediaInfoDLL/MediaInfoDLL.py ${pkgdir}/usr/lib/python2.7/site-packages/MediaInfoDLL.py
    install -Dm644 ${_pkgname}-${pkgver}/LICENSE ${pkgdir}/usr/share/licenses/$pkgname/LICENSE
}
```

**Comment by linux-man** [comment]
Thank you @Corax26. I guess I like to [KISS](https://wiki.archlinux.org/index.php/arch_terminology#KISS) :smiley: 
@yochananmarqos I'm really not the right person to validate your PKGBUILD... you need an ARCH power user.

**Comment by yochananmarqos** [comment]
I think I'll go ahead and add both packages to the AUR. If either of you @linux-man @Corax26 want to be a contributor, give me your username & email address (optional) and I'll add you. I'll add the links when they're up.

EDIT: They're up: [`nemo-mediainfo`](https://aur.archlinux.org/packages/nemo-mediainfo-tab/) tab & [`python-mediainfodll`](https://aur.archlinux.org/packages/python-mediainfodll/)

**Comment by linux-man** [comment]
Good. It looks like you solved your issue.
Since you had all this trouble, there are 2 nemo-mediainfo-tab forks that you can package with minimum changes: [nautilus-mediainfo](https://github.com/linux-man/nautilus-mediainfo) and [caja-mediainfo-tab](https://github.com/linux-man/caja-mediainfo-tab).
Even if you aren't up to create those packages, the python-mediainfodll is essential to all of them, so thank you a lot for your work.

**Comment by yochananmarqos** [comment]
You know what just dawned on me after uploading `python-mediainfodll`? It will work with both Python 2 & 3, so now [`python-mediainfodll`](https://aur.archlinux.org/packages/python-mediainfodll/) is for Python 3 and [`python2-mediainfodll`](https://aur.archlinux.org/packages/python2-mediainfodll/) is for Python 2. Both [`nautilus-mediainfo`](https://aur.archlinux.org/packages/nautilus-mediainfo/) and [`caja-mediainfo-tab`](https://aur.archlinux.org/packages/caja-mediainfo-tab/) are now also in the AUR.

**Comment by linux-man** [comment]
Great work! About python-mediainfodll/python2-mediainfodll, I would add dependencies to python/python2 just because it makes sense.
Fell free to close the issue if everything is working.
Thank you again. :1st_place_medal:

**Comment by yochananmarqos** [comment]
Whoops! I can't believe I forgot to add python to the dependencies. Fixed it.

**Comment by ghost** [comment]
@yochananmarqos Awesome, great job! I will go ahead and install your packages, much better than having stuff in my $HOME for sure \o/ I'll report any issue/remark on the AUR directly. If you wish, you can add me as a co-maintainer, my AUR username is Corax.

**Comment by yochananmarqos** [comment]
@Corax26 I added you as a Co-Maintainer for all 5 packages. There probably won't be much maintaining to do; however if you see a way to improve anything feel free.

**Comment by ghost** [comment]
@yochananmarqos Cool! I'm only using nemo-medainfo-tab and python2-mediainfodll so I'm unlikely to look at the others, but if needed I can help with them as well.

**Comment by linux-man** [comment]
@yochananmarqos @Corax26 nemo-mediainfo-tab is out-of-date.

**Comment by yochananmarqos** [comment]
@linux-man Whoops, missed that one. Done!
