### ISSUE TITLE
Language localisation idea

### ISSUE THREAD

**Issue by seigneurfuo** [linux-man/nemo-mediainfo-tab#4]
First at all, nice work ! This is the applet that I searched for a while !

I have found a way to make the language localisation work:
My native language is French and I like to have most of my programs in French. Unfortunately this output of the MediaInfoDLL is in English by default. 

By adding a simple line to the nemo-mediainfo-tab.py; I was able to change the MediaInfoDLL output language to French. So when I use the MediaInfo tab in Nemo, all the text is localised. Here the instruction:

MI.Option_Static("language", filepath)

But there is one problem (at least for me): MediaInfo translations files (https://github.com/MediaArea/MediaInfo/tree/master/Source/Resource/Plugin/Language) aren't packaged on ArchLinux (I wonder if there is the same for Debian and Ubuntu).

So for the moment, the only way to get the translation working is to put translation file somewhere and change the path in the nemo-mediainfo-tab.py file, wich is not "user friendly".

Proposal: Adding the translation file to a defined path (for exemple ~/.config/nemo-mediainfo-tab/translations) and the applet will check if the folder content. If it's empty it run normaly but if the folder contains a translation file, the applet calls the MediaInfoDLL option to load the language file.

Let me know what you think about this idea

Best regards.

**Comment by seigneurfuo** [comment]
Something like that:
    [...]
    MI.Option_Static("Complete")

    translation_path = "/usr/share/nemo-mediainfo-tab/translation"
    translation_files = os.listdir(translation_path)
    if os.path.exists(translation_path) and len(translation_files) == 1:
      translation_file = "file://{}".format(os.path.join(translation_path, translation_files[0]))
      MI.Option_Static("Language", translation_file)

**Comment by seigneurfuo** [comment]
Something like this: https://github.com/seigneurfuo/nemo-mediainfo-tab/commit/e843a313622f56d00dd9c09f90116618d4eac7dc

It takes the first file found on /usr/share/nemo-mediainfo-tab/translation.

**Comment by linux-man** [comment]
I committed some changes. What do you think?
You're right: translation files were not packaged by anyone, so I decided to add them to the extension.
Can you test it?

**Comment by seigneurfuo** [comment]
I think your python script is way better than mine ! Auto locale detectection is great !

For translation files, I think putting them all in /usr/share/nemo-python/extensions is a bad idea, or maybe considering rename thoses files with the project name; something like that: nemo-mediainfo-tab-<locale>.csv.

I think it could create conflicts with any other applets if the translations files keep theres actuals names.

**Comment by linux-man** [comment]
The files are in /usr/share/nemo-python/extensions/nemo-mediainfo-tab/locale.
It's impossible to create a conflict with a path like this...
Since is relative to the script position, code works on systems with a different extension path.
It don't pollute /usr/share folder.
I think it's a not-bad solution.

**Comment by seigneurfuo** [comment]
Ho ! I got wrong, I didn't understand how Debian packaging system works.
Yes in that case I dont have any modifications to add. I will test this to see if it works for me.

**Comment by seigneurfuo** [comment]
So, it works ! To test it out, i just use the .py script and the fr.csv file. French locale is loader from the file without any problem.

**Comment by linux-man** [comment]
Then, v.0.3, here we go!
I'll update README.md with your name, if you don't mind.

**Comment by seigneurfuo** [comment]
No problem !

Will you push this 0.3 update on your other flavors too (the nautilus and mate version ?)

**Comment by linux-man** [comment]
Done.
@yochananmarqos and @Corax26, time to update?

**Comment by yochananmarqos** [comment]
@linux-man Updated all three.

**Comment by linux-man** [comment]
Sorry, but I think you forgot to copy nemo-mediainfo-tab/locale (and nautilus-mediainfo/locale, caja-mediainfo-tab/locale) to the extensions folder. I tried with nautilus-mediainfo.
I also noticed that arch has a compatibility problem between python-nautilus and python2-nautilus. Not much can be done right now.

**Comment by linux-man** [comment]
One issue: nemo-mediainfo-tab/locale should be copied to /usr/share/nautilus-python/extensions/.

**Comment by yochananmarqos** [comment]
@linux-man Fixed. 
Shouldn't the locale files be in `/usr/share/locale`? For example: `/usr/share/locale/en_GB/LC_MESSAGES/nemo-mediainfo-tab.csv`.

**Comment by linux-man** [comment]
These aren't normal locales, like the mo files you can find, and in my mind there's a difference between an application and an extension: it's like a 2nd class app who doesn't have the right to spread everywhere like an application does. Maybe it's just me...

It's almost there :grin: 
cp -a ${pkgname}-${pkgver}/nemo-extension/${pkgname}/locale/. ${pkgdir}/usr/share/nemo-python/extensions/nemo-mediainfo-tab/locale
or
cp -a ${pkgname}-${pkgver}/nemo-extension/${pkgname}/locale/. ${pkgdir}/usr/share/nemo-python/extensions/${pkgname}/locale

**Comment by yochananmarqos** [comment]
@linux-man Whoops. Got it.

I noticed other extensions install their other files in their own folder in `/usr/share/` rather than the extension folder. It might be tidier to have the locale folder in `/usr/share/nemo-mediainfo-tab/` instead.

**Comment by linux-man** [comment]
I see your point. I'm a little torn apart about that.
As a plus, this way the extension can be installed at .local with no changes.
I'll think about it.
