### ISSUE TITLE
Not working with nemo-python 4.0

### ISSUE THREAD

**Issue by ghost** [linux-man/nemo-mediainfo-tab#7]
nemo-python 4.0 has been ported to Python 3 (see https://blog.linuxmint.com/?p=3644), and it seems that nemo-mediainfo-tab is no longer functional. It does appear in the extension list, and I can execute nemo-mediainfo-tab.py with Python 3 without error (so no library is missing), but no tab appears in the properties. I'll happily provide more debug info, I just don't know what else to look at.

**Comment by linux-man** [comment]
That was fast! Fortunately some Arch users have already warned about future changes. You can find a Branch: python3 which hopefully will work with python-nemo > 3.9.
Can you download last release https://github.com/linux-man/nemo-mediainfo-tab/releases/tag/v0.3-python3 and replace /usr/share/nemo-python/extensions/nemo-mediainfo-tab.py to see if it works?

**Comment by linux-man** [comment]
You'll probably need python-mediainfodll. It's already on AUR.

**Comment by ghost** [comment]
The v0.3-python3 branch works for me, thanks! Do you plan on keeping this branch for the time being, or are you planning to support both on the main branch? I'll update the PKGBUILD accordingly.

**Comment by linux-man** [comment]
After Linux Mint 19.1 release (around Christmas), I pretend to update main branch to python3 and create a python2 legacy branch.
During Mint 19.x life (4 years, right?) I should offer both sources and packages.
nautilus-mediainfo also has a python3 branch waiting to be used when needed.

**Comment by ghost** [comment]
All right, I will update the PKGBUILD to use the v0.3-python3 branch then, at least for now.

**Comment by linux-man** [comment]
@Corax26 I was able to adapt the code to run on both python versions. Nothing else is new. You can keep the python3 branch or update. Your call.

**Comment by ghost** [comment]
@linux-man Sorry for the delay, well done! I've bumped the AUR package to v0.4, so the -python3 releases are no longer needed, at least for Arch :) Closing the issue.
