### ISSUE TITLE
What about removing METADATE_BLOCK_PICTURE row ?

### ISSUE THREAD

**Issue by seigneurfuo** [linux-man/nemo-mediainfo-tab#8]
Hi. I think the METADATE_BLOCK_PICTURE data is useless.

- It tooks a large amount of space by set the windows width out of the screen (even on 1920x1080 resolution).

- I thinks nobody will use it: it just display embeded audio picture on an encoded string.

What do you think about this ?

**Comment by seigneurfuo** [comment]
![image](https://user-images.githubusercontent.com/20669563/53689393-1ed06880-3d55-11e9-97d8-bef7a695a0d5.png)

Here a screenshot of what appears when an file has METADATE_BLOCK_PICTURE tag.

**Comment by linux-man** [comment]
Yes. It's an useless property to see. I never found a picture with this data. Can you send me a sample?

**Comment by seigneurfuo** [comment]
In my case this "tag" appears after converting an .flac audio file to an ogg with "Soundconverter" software (https://soundconverter.org/).

I' am writing a small "patch". I send it to you before Wednesday

**Comment by linux-man** [comment]
Thanks. I tried the same conversion but that tag doesn't appear. Please send me the "guilty" file when you have time. No worries. It looks like a rare situation.

**Comment by JeromeMartinez** [comment]
METADATA_BLOCK_PICTURE is the name in FLAC spec for the cover picture, data you see in the output is the picture data because it is not ignored by MediaInfo as it is not aware of such tag name for cover picture in OGG/Vorbis. It may be smarter to provide a file to MediaInfo developers so they can hide such useless output for every MediaInfo users instead of implementing it only in Nemo.

**Comment by linux-man** [comment]
I committed a possible solution but would like to try it with your file.
I will update the extension because even if @JeromeMartinez corrects the issue it will take a long time before the library is updated (if ever) at the repositories.

**Comment by seigneurfuo** [comment]
@linux-man Here is file for testing: 
https://send.firefox.com/download/1246513b37/#PJTP01OjptiVoHlp9WJuoA (ogg format)
https://send.firefox.com/download/a87bf6125f/#t7R-pr_G1SFS3fFjZ1hbLw (flac format)

**Comment by seigneurfuo** [comment]
I packaged and test your solution on my distibution: It seems to fix the "issue". Thanks !
